version: '3'
services:
  db:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - data-railsapi:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: admin

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/railsapi
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  data-railsapi:
    external: true
